sudo: required
services:
  - docker

before_install:
  - docker build -t syjn99/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true syjn99/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-demo-frontend"
  env: "Docker-demo-frontend-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-661330646336"
  bucket_path: "docker-demo-frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_KEY
